[[LLVMBootstrap_libLLVM]]
arch = "x86_64"
git-tree-sha1 = "1ea41185508797354ae64d6da7a481b8cb2202eb"
libc = "glibc"
os = "linux"

    [[LLVMBootstrap_libLLVM.download]]
    sha256 = "1e473b9ccc7d009176e11d9acd9217bebb78685d578365083a87329bfc0e7c91"
    url = "https://github.com/staticfloat/LLVMBootstrap_libLLVM_jll.jl/releases/download/v17.0.0-GCCBootstrap-x86_64-linux-gnu/LLVMBootstrap_libLLVM-v17.0.0-x86_64-linux-gnu.tar.gz"

[[LLVMBootstrap_libLLVM-build_log]]
arch = "x86_64"
git-tree-sha1 = "b868bef6902668fcf9559643d07c8c4ec881b715"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMBootstrap_libLLVM-build_log.download]]
    sha256 = "047943d583f28670d4da3e7641d1e352abadb16f1b23216b43e67cc1f16643a2"
    url = "https://github.com/staticfloat/LLVMBootstrap_libLLVM_jll.jl/releases/download/v17.0.0-GCCBootstrap-x86_64-linux-gnu/LLVMBootstrap_libLLVM-build_log-v17.0.0-x86_64-linux-gnu.tar.gz"

[[LLVMBootstrap_libLLVM-extract_log]]
arch = "x86_64"
git-tree-sha1 = "8e98468efdbc151d67889a87db0dc91e0a3efb17"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMBootstrap_libLLVM-extract_log.download]]
    sha256 = "3c13ddecfef0ec613592018cda106eabc287fe741fbefdc0e82d8c6ac233111a"
    url = "https://github.com/staticfloat/LLVMBootstrap_libLLVM_jll.jl/releases/download/v17.0.0-GCCBootstrap-x86_64-linux-gnu/LLVMBootstrap_libLLVM-extract_log-v17.0.0-x86_64-linux-gnu.tar.gz"
