[[LLVMBootstrap_libLLVM]]
arch = "x86_64"
git-tree-sha1 = "1ea41185508797354ae64d6da7a481b8cb2202eb"
libc = "glibc"
os = "linux"

    [[LLVMBootstrap_libLLVM.download]]
    sha256 = "b8f5a4bb0dae5ebc589bb423fb3097512cbb8c689406bddb542375c92afa5cdf"
    url = "https://github.com/staticfloat/LLVMBootstrap_libLLVM_jll.jl/releases/download/v17.0.0-GCCBootstrap-x86_64-linux-gnu/LLVMBootstrap_libLLVM-v17.0.0-x86_64-linux-gnu.tar.gz"

[[LLVMBootstrap_libLLVM-build_log]]
arch = "x86_64"
git-tree-sha1 = "ca2d7a516cdede163a9aced02415c1480a0c5f6c"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMBootstrap_libLLVM-build_log.download]]
    sha256 = "efff0e03a7becb0d7206966492536453905944ff8374642da569d7c3bc8c2523"
    url = "https://github.com/staticfloat/LLVMBootstrap_libLLVM_jll.jl/releases/download/v17.0.0-GCCBootstrap-x86_64-linux-gnu/LLVMBootstrap_libLLVM-build_log-v17.0.0-x86_64-linux-gnu.tar.gz"

[[LLVMBootstrap_libLLVM-extract_log]]
arch = "x86_64"
git-tree-sha1 = "32e1ffe7d0a6bdade4f0030d6619a7f141036774"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMBootstrap_libLLVM-extract_log.download]]
    sha256 = "dfcae39fe97da33ce2f11b5e5c3bd4b34ec540eb03b82613bc11826e3b8691fa"
    url = "https://github.com/staticfloat/LLVMBootstrap_libLLVM_jll.jl/releases/download/v17.0.0-GCCBootstrap-x86_64-linux-gnu/LLVMBootstrap_libLLVM-extract_log-v17.0.0-x86_64-linux-gnu.tar.gz"
