[[LLVMBootstrap_libLLVM]]
arch = "x86_64"
git-tree-sha1 = "1ea41185508797354ae64d6da7a481b8cb2202eb"
libc = "glibc"
os = "linux"

    [[LLVMBootstrap_libLLVM.download]]
    sha256 = "c29e8f2a55da2e7893fc39d2f8e586c83f8ea1c7e023094d10d67964f138ebe4"
    url = "https://github.com/staticfloat/LLVMBootstrap_libLLVM_jll.jl/releases/download/v17.0.0/LLVMBootstrap_libLLVM-v17.0.0-x86_64-linux-gnu.tar.gz"
[[LLVMBootstrap_libLLVM]]
arch = "aarch64"
git-tree-sha1 = "f7858c2a49a00b88ba77cbc67d15bd0bc63c383b"
libc = "glibc"
os = "linux"

    [[LLVMBootstrap_libLLVM.download]]
    sha256 = "2f674b02a768eef81ae56ecf2c8dfada21bffc92ee15e35728f30ea44f8b6085"
    url = "https://github.com/staticfloat/LLVMBootstrap_libLLVM_jll.jl/releases/download/v17.0.0/LLVMBootstrap_libLLVM-v17.0.0-aarch64-linux-gnu.tar.gz"

[[LLVMBootstrap_libLLVM-build_log]]
arch = "x86_64"
git-tree-sha1 = "38601cccccb0c7aff778d43c9e5f3129e52eedb7"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMBootstrap_libLLVM-build_log.download]]
    sha256 = "333ea75bc6a09272bd1821d777e0b90ca9a06f997a479f94049ab71e2a927f3a"
    url = "https://github.com/staticfloat/LLVMBootstrap_libLLVM_jll.jl/releases/download/v17.0.0/LLVMBootstrap_libLLVM-build_log-v17.0.0-x86_64-linux-gnu.tar.gz"
[[LLVMBootstrap_libLLVM-build_log]]
arch = "aarch64"
git-tree-sha1 = "156a01ae1adedd1c5c909e4f3d479ca58d322874"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMBootstrap_libLLVM-build_log.download]]
    sha256 = "82d4e7a1ac2c52936fb39a50f9679908c448ab91d7ba8b6b378923a8364a4cbf"
    url = "https://github.com/staticfloat/LLVMBootstrap_libLLVM_jll.jl/releases/download/v17.0.0/LLVMBootstrap_libLLVM-build_log-v17.0.0-aarch64-linux-gnu.tar.gz"

[[LLVMBootstrap_libLLVM-extract_log]]
arch = "x86_64"
git-tree-sha1 = "b96484ba90c47ae9cf483613d8ba062757a590f9"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMBootstrap_libLLVM-extract_log.download]]
    sha256 = "21403913348e445a9812d8b6e68f05a08ad2bbef13e24b85318621b8c555cee4"
    url = "https://github.com/staticfloat/LLVMBootstrap_libLLVM_jll.jl/releases/download/v17.0.0/LLVMBootstrap_libLLVM-extract_log-v17.0.0-x86_64-linux-gnu.tar.gz"
[[LLVMBootstrap_libLLVM-extract_log]]
arch = "aarch64"
git-tree-sha1 = "95fa848e08e166c3b1b75b9f97b3059623f3be86"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMBootstrap_libLLVM-extract_log.download]]
    sha256 = "b353388dececeb322b824f853ac29f62a2372a83cf1ec85e42de1cad1767cef2"
    url = "https://github.com/staticfloat/LLVMBootstrap_libLLVM_jll.jl/releases/download/v17.0.0/LLVMBootstrap_libLLVM-extract_log-v17.0.0-aarch64-linux-gnu.tar.gz"
