[[LLVMBootstrap_libLLVM]]
arch = "x86_64"
git-tree-sha1 = "1ea41185508797354ae64d6da7a481b8cb2202eb"
libc = "glibc"
os = "linux"

    [[LLVMBootstrap_libLLVM.download]]
    sha256 = "f2d5722ecc7c336547f901a343cfb68d5c5145aae881483b9dbca57ad05a276e"
    url = "https://github.com/staticfloat/LLVMBootstrap_libLLVM_jll.jl/releases/download/v17.0.0/LLVMBootstrap_libLLVM-v17.0.0-x86_64-linux-gnu.tar.gz"
[[LLVMBootstrap_libLLVM]]
arch = "aarch64"
git-tree-sha1 = "f7858c2a49a00b88ba77cbc67d15bd0bc63c383b"
libc = "glibc"
os = "linux"

    [[LLVMBootstrap_libLLVM.download]]
    sha256 = "1c516d16193f6d1d45c114aec14f261b7bb5a94f653744bd1063d7487bc4e4e4"
    url = "https://github.com/staticfloat/LLVMBootstrap_libLLVM_jll.jl/releases/download/v17.0.0/LLVMBootstrap_libLLVM-v17.0.0-aarch64-linux-gnu.tar.gz"

[[LLVMBootstrap_libLLVM-build_log]]
arch = "x86_64"
git-tree-sha1 = "243683d8ed52960bd8133b6873acf5326ec4f207"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMBootstrap_libLLVM-build_log.download]]
    sha256 = "1d1641a25a91b24d8b27e77073289473597d473e344290a3a99c03de829db65e"
    url = "https://github.com/staticfloat/LLVMBootstrap_libLLVM_jll.jl/releases/download/v17.0.0/LLVMBootstrap_libLLVM-build_log-v17.0.0-x86_64-linux-gnu.tar.gz"
[[LLVMBootstrap_libLLVM-build_log]]
arch = "aarch64"
git-tree-sha1 = "e73e45729443644e8b2d317400cb05046cba72e2"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMBootstrap_libLLVM-build_log.download]]
    sha256 = "ca12378f84046e76bc8d7dab0896feafdec90ced004d4e46627b5c9858446d85"
    url = "https://github.com/staticfloat/LLVMBootstrap_libLLVM_jll.jl/releases/download/v17.0.0/LLVMBootstrap_libLLVM-build_log-v17.0.0-aarch64-linux-gnu.tar.gz"

[[LLVMBootstrap_libLLVM-extract_log]]
arch = "x86_64"
git-tree-sha1 = "f9cc93c5786cb11359a1cc6f2a951dd702b23376"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMBootstrap_libLLVM-extract_log.download]]
    sha256 = "46ec34fe8453c0380d56c9deaceb0bd9aaa783504f880c25a03e41a77ba75c14"
    url = "https://github.com/staticfloat/LLVMBootstrap_libLLVM_jll.jl/releases/download/v17.0.0/LLVMBootstrap_libLLVM-extract_log-v17.0.0-x86_64-linux-gnu.tar.gz"
[[LLVMBootstrap_libLLVM-extract_log]]
arch = "aarch64"
git-tree-sha1 = "7ab92e3a518a7585bc1c3006d2e187e6e4316bb5"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMBootstrap_libLLVM-extract_log.download]]
    sha256 = "3d83a6137b04a1d9b4861b989aa80c8968574a5689d8fa5b7ea7bffa816a9daf"
    url = "https://github.com/staticfloat/LLVMBootstrap_libLLVM_jll.jl/releases/download/v17.0.0/LLVMBootstrap_libLLVM-extract_log-v17.0.0-aarch64-linux-gnu.tar.gz"
