[[LLVMBootstrap_libLLVM]]
arch = "aarch64"
git-tree-sha1 = "75b7504ccdf1615997b5faaaf7004adfeb6b275d"
libc = "glibc"
os = "linux"

    [[LLVMBootstrap_libLLVM.download]]
    sha256 = "d5ea7a719c9ab67e08a687365afdb40833ddb3a8e31c922fa28af3078ca72dea"
    url = "https://github.com/staticfloat/LLVMBootstrap_libLLVM_jll.jl/releases/download/v17.0.0-GCCBootstrap-aarch64-linux-gnu/LLVMBootstrap_libLLVM-v17.0.0-aarch64-linux-gnu.tar.gz"

[[LLVMBootstrap_libLLVM-build_log]]
arch = "aarch64"
git-tree-sha1 = "8dd110f2ddde38179ff6fe4ee62e7337a5a1c862"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMBootstrap_libLLVM-build_log.download]]
    sha256 = "57bed2c950571384bec0aa77878fc829144996c40fbdbe86987468c3c5d344cb"
    url = "https://github.com/staticfloat/LLVMBootstrap_libLLVM_jll.jl/releases/download/v17.0.0-GCCBootstrap-aarch64-linux-gnu/LLVMBootstrap_libLLVM-build_log-v17.0.0-aarch64-linux-gnu.tar.gz"

[[LLVMBootstrap_libLLVM-extract_log]]
arch = "aarch64"
git-tree-sha1 = "3c2dc84b6305766af158837d009bbb69156f4364"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMBootstrap_libLLVM-extract_log.download]]
    sha256 = "1fe39bd6b81d133ac4b0e275998903e1ef61f9d17cf01e20b11f006b5f7b2769"
    url = "https://github.com/staticfloat/LLVMBootstrap_libLLVM_jll.jl/releases/download/v17.0.0-GCCBootstrap-aarch64-linux-gnu/LLVMBootstrap_libLLVM-extract_log-v17.0.0-aarch64-linux-gnu.tar.gz"
