[[LLVMBootstrap_libLLVM]]
arch = "x86_64"
git-tree-sha1 = "1ea41185508797354ae64d6da7a481b8cb2202eb"
libc = "glibc"
os = "linux"

    [[LLVMBootstrap_libLLVM.download]]
    sha256 = "7cbe628f5b30d08521611efbaa1d3d8ea53fdfd2bb9538aac14e6cdf9937d9aa"
    url = "https://github.com/staticfloat/LLVMBootstrap_libLLVM_jll.jl/releases/download/v17.0.0/LLVMBootstrap_libLLVM-v17.0.0-x86_64-linux-gnu.tar.gz"
[[LLVMBootstrap_libLLVM]]
arch = "aarch64"
git-tree-sha1 = "f7858c2a49a00b88ba77cbc67d15bd0bc63c383b"
libc = "glibc"
os = "linux"

    [[LLVMBootstrap_libLLVM.download]]
    sha256 = "2ee1c20083bf8b948c3d36f024064839cf01a8440ec6848f0114348848de2061"
    url = "https://github.com/staticfloat/LLVMBootstrap_libLLVM_jll.jl/releases/download/v17.0.0/LLVMBootstrap_libLLVM-v17.0.0-aarch64-linux-gnu.tar.gz"

[[LLVMBootstrap_libLLVM-build_log]]
arch = "x86_64"
git-tree-sha1 = "6b20d91aec3bf0a7e96c7093569770312f6ee308"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMBootstrap_libLLVM-build_log.download]]
    sha256 = "c46458391c8139ad1a55b69cbbfe69ce63ff359646a0d92cb308dceb426adc53"
    url = "https://github.com/staticfloat/LLVMBootstrap_libLLVM_jll.jl/releases/download/v17.0.0/LLVMBootstrap_libLLVM-build_log-v17.0.0-x86_64-linux-gnu.tar.gz"
[[LLVMBootstrap_libLLVM-build_log]]
arch = "aarch64"
git-tree-sha1 = "2423e47a6bf078711f89bdeaec81fcd5507a2eb9"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMBootstrap_libLLVM-build_log.download]]
    sha256 = "36343093dbd622f2edccdaa6a64dbe3cdfb5cd06123b36af09776c41f4762755"
    url = "https://github.com/staticfloat/LLVMBootstrap_libLLVM_jll.jl/releases/download/v17.0.0/LLVMBootstrap_libLLVM-build_log-v17.0.0-aarch64-linux-gnu.tar.gz"

[[LLVMBootstrap_libLLVM-extract_log]]
arch = "x86_64"
git-tree-sha1 = "919b18cba100874632b1219f10569b2b21975b3c"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMBootstrap_libLLVM-extract_log.download]]
    sha256 = "ddccff893c37cfb9fbdf0c56c3756b03bb0db2fa869806a44fff3632e4fe22d3"
    url = "https://github.com/staticfloat/LLVMBootstrap_libLLVM_jll.jl/releases/download/v17.0.0/LLVMBootstrap_libLLVM-extract_log-v17.0.0-x86_64-linux-gnu.tar.gz"
[[LLVMBootstrap_libLLVM-extract_log]]
arch = "aarch64"
git-tree-sha1 = "aacdf48f4c877ee938aaca2a24ded151b33bf1f5"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMBootstrap_libLLVM-extract_log.download]]
    sha256 = "e219a6d114328412d3940b4a8a7d1bcdfbebbb86319dcfac755abab4e54d6d07"
    url = "https://github.com/staticfloat/LLVMBootstrap_libLLVM_jll.jl/releases/download/v17.0.0/LLVMBootstrap_libLLVM-extract_log-v17.0.0-aarch64-linux-gnu.tar.gz"
