[[LLVMBootstrap_libLLVM]]
arch = "x86_64"
git-tree-sha1 = "1ea41185508797354ae64d6da7a481b8cb2202eb"
libc = "glibc"
os = "linux"

    [[LLVMBootstrap_libLLVM.download]]
    sha256 = "c544424a1889747436818b69c299e4fe072bb2573ff1310c730d8bf4b79a9f37"
    url = "https://github.com/staticfloat/LLVMBootstrap_libLLVM_jll.jl/releases/download/v17.0.0/LLVMBootstrap_libLLVM-v17.0.0-x86_64-linux-gnu.tar.gz"
[[LLVMBootstrap_libLLVM]]
arch = "aarch64"
git-tree-sha1 = "f7858c2a49a00b88ba77cbc67d15bd0bc63c383b"
libc = "glibc"
os = "linux"

    [[LLVMBootstrap_libLLVM.download]]
    sha256 = "2259ea11256217c6a2ecd377f0b33fa76e2f5498419f154317da62c34fadcb47"
    url = "https://github.com/staticfloat/LLVMBootstrap_libLLVM_jll.jl/releases/download/v17.0.0/LLVMBootstrap_libLLVM-v17.0.0-aarch64-linux-gnu.tar.gz"

[[LLVMBootstrap_libLLVM-build_log]]
arch = "x86_64"
git-tree-sha1 = "3336dae1546328aa0ef421e8f00890cffd0d29b5"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMBootstrap_libLLVM-build_log.download]]
    sha256 = "e552ee53818266154402e53d52721c7cce63f52aa1814725ff239890c0e65dbf"
    url = "https://github.com/staticfloat/LLVMBootstrap_libLLVM_jll.jl/releases/download/v17.0.0/LLVMBootstrap_libLLVM-build_log-v17.0.0-x86_64-linux-gnu.tar.gz"
[[LLVMBootstrap_libLLVM-build_log]]
arch = "aarch64"
git-tree-sha1 = "e6b0f9d9d9b20f8601759b7d96e993a771ce4730"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMBootstrap_libLLVM-build_log.download]]
    sha256 = "ca062197b3859b0b0f67ddbed4b7f29c714971c5f132590056d9949f40f73384"
    url = "https://github.com/staticfloat/LLVMBootstrap_libLLVM_jll.jl/releases/download/v17.0.0/LLVMBootstrap_libLLVM-build_log-v17.0.0-aarch64-linux-gnu.tar.gz"

[[LLVMBootstrap_libLLVM-extract_log]]
arch = "x86_64"
git-tree-sha1 = "b831df6e5f02ebbc5a8bd800aaa7308795268ad5"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMBootstrap_libLLVM-extract_log.download]]
    sha256 = "df28fa21f4c43584efa2e73bd7601526969f1d61f8a4744a769f8400fbfbdd63"
    url = "https://github.com/staticfloat/LLVMBootstrap_libLLVM_jll.jl/releases/download/v17.0.0/LLVMBootstrap_libLLVM-extract_log-v17.0.0-x86_64-linux-gnu.tar.gz"
[[LLVMBootstrap_libLLVM-extract_log]]
arch = "aarch64"
git-tree-sha1 = "d2c31f6924e8a5537acb7c1991455d37bcc1623a"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMBootstrap_libLLVM-extract_log.download]]
    sha256 = "12beeea361cf36b5f957226300554e54fb7225944d3598e7f2aacc551e466823"
    url = "https://github.com/staticfloat/LLVMBootstrap_libLLVM_jll.jl/releases/download/v17.0.0/LLVMBootstrap_libLLVM-extract_log-v17.0.0-aarch64-linux-gnu.tar.gz"
